name: testupdater
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ipykernel
  - pip
  - cudatoolkit=11.8
  - pip:
      - accelerate==1.0.1
      - aiohttp==3.10.10
      - annotated-types==0.7.0
      - anyio==4.6.2.post1
      - beautifulsoup4==4.12.3
      - cattrs==24.1.2
      - codebleu==0.6.1
      - datasets==3.0.2
      - dill==0.3.8
      - flagembedding==1.2.11
      - fsspec==2024.9.0
      - gitpython==3.1.43
      - httpx==0.27.2
      - huggingface-hub==0.26.1
      - javalang==0.13.0
      - jedi-language-server==0.41.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - langchain-core==0.2.43
      - langchain-openai==0.1.25
      - langchain-text-splitters==0.2.4
      - langsmith==0.1.137
      - lxml==5.3.1
      - matplotlib-inline
      - networkx==3.4.2
      - numpy==1.26.4
      - openai==1.52.2
      - orjson==3.10.10
      - pandas==2.2.3
      - peft==0.13.2
      - psutil==6.1.0
      - pyarrow==17.0.0
      - pydantic==1.10.5
      - regex==2024.9.11
      - requests==2.32.3
      - safetensors==0.4.5
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - sentence-transformers==3.2.1
      - sympy==1.13.1
      - tiktoken==0.8.0
      - tokenizers==0.20.1
      - torch==2.5.0
      - tqdm==4.66.5
      - transformers==4.46.0
      - tree-sitter==0.21.0
      - tree-sitter-java==0.21.0
      - triton==3.1.0
      - typing-extensions==4.12.2
      - yarl==1.16.0
